### ISSUE TITLE
Clipping execute does not properly.

### ISSUE THREAD

**Issue by findux** [apicici/clipper-lua#2]
Hi. As seen in the picture, after the 59th line, I get an error like the one on the screen. Isn't that the correct usage?
I am using Löve2D 11.3.
![execute issue](https://user-images.githubusercontent.com/4825408/209434838-9141cfa6-c040-41a8-aab8-8c59cedd0e5d.PNG)

**Comment by apicici** [comment]
The error is caused one of the paths passed to the `Clipper` object is open, but the `Execute` call is given a `Paths` object as the solution parameter. According to the [documentation](http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Classes/Clipper/Methods/Execute.htm):
> when open paths are passed to a Clipper object, the user must use a PolyTree object as the solution parameter, otherwise an exception will be raised.

In this case a `PolyTree` object should be used to store the solution:
```lua
local ress = clipperLib.PolyTree()
cl:Execute(clipperLib.ctIntersection, ress)
```
